dist: trusty

language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  global:
    - STAGE=prod
    - secure: 'b4G1Vv/KLkiw3dtgB8Lmy6idvoQWBkOyEYuCGW4n4frc/mEszLc/ruZ9qx1u2dNY7Rd6iGqXJhuqi6epIPZ6FfcI2s/Xe30Rz02sMSZEnPnfwMgrT3Oz08G9l489pQSkSILjrPSzZJ/pd+jN2GcwFfYRe1gXwQXlFSdUBay9eKv8QLpA6w0B3u90hrSzB3B+sHLZ1RkFA/H696ylbvfkvpDsgGxu8aebBQqftlDnpuVLlofSu8aF2jOkfVpnR9h0pAh1xBFh69TPsKDpUZCj3J0ezlmESwcd5Hd1zwQAtxZPmkKZyhW9OsP3vNKwHNK7HDAGu9DzGsvPmfN1MQsHJVTl9KfLkNO9to8oUlMwatXZqh7kedgcDFzQG165nAHKvUEI7MamEFJzdwS12hZwLLT5XSmnGO1Er76BkWcZ1JIZLlGnvG8PdIqia8Lveu+IZ1dYkbjNf/NDZXFdXuAbyHT+9b16bHHUw4Dc5l72LDcZ1b6LiZ5FFxS3kZOHar60F637JkIzkHKj4JQosgU5tYimroME95hyhiMZGcSudO5f/tfOYgU25lytYL1KY0tLvpiQmyJkqNbPprXv3BPOYrSZHfPT/8E62EiHURmA+dyPYsh7sCE6Fw1Rt1woU2ldQ/usW+o8BtnMbT8L3aLO+qOi18K2T04NGXRaH7rhfY0='
    - secure: 'GeC5tb7PRYC0u/IsnGEBH0vbafYwLzdmeoKOCNPLX0y6rgucCghw1qw5MLEO8XeWeXoHHAhAA95QAeVF8EogN2nZF53XWLZJepn782LtJKwjCVnq+Xi5vpDRQeWN++x8JomzDsHYrDPQiLKVRKAPzCX14bIvYaq6lCwXPp/s61nP5j3tnVcvSoRf4Yjby/qc3UFDrNykIE0+Fy/VGirYK9FfE/hn8CkYOhQX0dzK5CKuUwiPD72soKVezA3ZggyLB83FDJvBJK4R2p8khCgt6uH904iRGyQsSIonO4yRcOp1/r8MxIHj1KNVoQD8o+mEewIDfQe8vlStE4n8KIteqRbcFD8Qc9D+h9efNNV6AH8uj6fRrj+a+mgMeZkqIF+Y511NIGHfQ4e4XlHJz0tlsG5d/jyZPlFZikFfUN9qM0bv/Ezd5kzmt8dAj0VuScnhZt0Ju7Gtksdy4T5eY2PTqIJbKqecUYjwQgLcUCYIiActlQWdynS45ytTd/t/1nPKeocxERhKfS78tW28WrS/SX2Cpp2bO6Ihw5ksIjCvyYI7qXpd5DR7kXf+SAtcGg/R1GSnJSFrskhbQ5xqkBSgPOTGr9pvCcDA4b5HICIUGs33X58rXXPIUDbOgfz2t6ST1jX8wI1CA0uckNfu4mSHBUPBMl8IT7I34Asv4IdrL20='
    - secure: 'OHAK2QhZoyfJRNScYwgdtIM+dqheJlbMFhIeXC5iNqVkYfdNFkw+n8YFA5T0VKnSstYqNHxnmpdAABS7qEtZ5FvK4TOS7jd+z9/F3yJSX2G54BoDWPoi88Qk9S1cy8xrd2xEuxKQDQDn1RuXRDYupshuGub6N9QQxar1pyLXCYmUxnSVUI5zM8qVwuI++yeelIBrhabz78utWZasO2qGPgDZY29ZA3gKfbcSL2KPyoXbszzCnag6sB77Uc8AvXw9FkrRcz+zCFb72UkkzkVLWsJLFFwYUzojAAAmJasiqSH9vOTaXpc0IJ2xdFqhfUuO7YHoogJNQmGaQqaEn7Yv6vPCvAa7EuOHj93RVgOteyCGqiBqUOn6x57/r6MnUDdX1ZOh6AUWWiBkwZPSga4rfhAWy5yduKvw87rGwx/glKVHjvNv8JX90+7h74ZJd1Zl1L0VQEfDb1mnaOQBx88eTXhT/EbDV1wHxCNYSmLl0e12liFWa6K2cemcvzfbffvRN8BKWWrP4tQDe3Y1Izs4T6QUemr7h3sgardObJs1ZKv3imZ1XV6VLcXbjkPkTssO+IitPH2u38C/r/pnJVdotW65IpkOx0jAlaWhDwnZWgklh1E+4JKqrJY0n3nlkpJ1A1FC1oTIpdl4lvD02zePJoaHFe43Q9/dqSwHSwq0SvY='
    - secure: 'nC2wOoMkKCLH6m4liKA1+8U//T2Z8Fcatgdy+Am9rMEmEts3ktPIXnrp7QcRib3O+Vh2c2/Rx6hrV2F4qIRuCyxRl3apJ0guzKGnaIAlwxaYQg/4DxCaGNmi3qu2jGJ7fIfkqGbaA/zNILCOCavXmcoBfY0DWtnoHxBSrb6AVytnX1wZFujlvrs/xZ50T2NAmlyLK9KdMWqe7/gR3isl3Yt2cKHSvSmTcYmWfPg+fZRKnU4grAfVaKuNIpykqM/podJbQ31VkPOjLceSSVImxmRxL0JF2eMgPqBlloTvbKYAWDQJsJwR7W/hiyNo/QZyoCQZxuhNaytuRVspMdlk9x2NYJASsV5MenAQnoZArc59kXpcktRSS8MZgmKMbhDIm2sp+4biANceyxrOuWn8tM0U43zQesb48Cht5QW9BOJMoyZHiOYBVll3pQyOVO9MpZjgI/uyQoqsS4YZcw9Gu3tp3TX8VLDK6I7M3NjqG+ox5zV1Iu16SlXg7Sh1M3ardNGIsrMP+503bl/4LG/sVr585N9v8S0WSxIZA4eAvUUycq/S1xM9lQkof7uAjOVl6lmuWAnQoZz5lQvbWmE9qhAFK3OzjVGUo7ALAt5jVZu4pJ5aDsFnt7UtmYAT3MwX/+uY5ukyfoYMDwCux3IJUaTAU6gt4v8oinOOeKpwGeU='

before_deploy:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-venv python3-pip

deploy:
  - provider: script
    script: make upload
    skip_cleanup: true
