name: Build and Test and Deploy

on: [push, pull_request]

env:
  STAGE: prod
  SAM_CLI_TELEMETRY: 0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  EK_USER_ID: ${{ secrets.EK_USER_ID }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build & test the application
        run: |
          npm ci
          npm run bootstrap
          npm test

      - name: Use Python 3
        if: github.ref == 'refs/heads/master'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Deploy the application
        if: github.ref == 'refs/heads/master'
        run: make upload
