name: Build and Test and Deploy

on:
  push:
    branches:
      - KillYourMaster
  pull_request:

env:
  STAGE: prod
  SAM_CLI_TELEMETRY: 0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  EK_USER_ID: ${{ secrets.EK_USER_ID }}
  GIT_SHA: ${{ github.sha }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Build & test the application
        run: |
          npm install
          npm test

      - name: Use Python 3
        if: github.ref == 'refs/heads/KillYourMaster'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Deploy the application
        if: github.ref == 'refs/heads/KillYourMaster' && !contains(github.event.head_commit.message, '[skip deployment]')
        run: make upload
